### ISSUE TITLE
TitleCase names, plus English language conventions for written variable names?

### ISSUE THREAD

**Issue by glwagner** [tomchor/Oceanostics.jl#19]
There are some quantities like `ShearProduction_x` that blend `TitleCase` and `snake_case` styles:

https://github.com/tomchor/Oceanostics.jl/blob/c7c6a8bea46d127f243e7c8f610edb7ce03ffcec/src/TurbulentKineticEnergyTerms.jl#L226

It's not a big deal, but I think it's best to "practice what we preach", if we are going to ask future developers to conform to style guidelines.

The other little inconsistency is that this name "blends" English-language conventions (where descriptors come first) with a "subscripting" convention (eg `_x` refers to the x-component). For example, in Oceananigans we use `ZDirection` rather than `Direction_z`.

We could call this instead `XShearProduction`; also `YShearProduction` and `ZShearProduction`.

This is also more consistent with some `Oceananigans` variables like `XFaceField` or `ZDirection`.

**Comment by tomchor** [comment]
The main reason why I did it that way was because `ShearProduction<TAB>` would show all components and so on with other quantities. But yeah, what you're saying makes sense. I'm okay with changing it to match the conventions better.

(btw, if you also want to contribute to the package lmk and I'll add you as a collaborator)
